# Generated by Django 2.0 on 2018-01-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recovery',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
