# Generated by Django 2.0 on 2018-01-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_user_type_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_plan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='type_plan',
            field=models.CharField(default='Free', max_length=50, verbose_name='Plan'),
        ),
    ]
