# Generated by Django 2.0.1 on 2018-01-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20180117_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='', verbose_name='Photo'),
        ),
    ]
