# Generated by Django 2.0.1 on 2018-01-28 14:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20180124_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo64',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Photo64'),
            preserve_default=False,
        ),
    ]
