# Generated by Django 2.0.1 on 2018-01-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_photo64'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='myPayPal',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Paypal_email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo64',
            field=models.TextField(default='', verbose_name='Photo64'),
        ),
    ]
