# Generated by Django 2.0.1 on 2018-02-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20180131_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='failedAttempts',
            field=models.IntegerField(default=5),
        ),
    ]
