# Generated by Django 2.0.1 on 2018-03-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_user_failedattempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customer_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Customer'),
        ),
    ]
