# Generated by Django 2.0.1 on 2018-04-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_user_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='attemptPayment',
            field=models.IntegerField(default=5, verbose_name='Payment Failure'),
        ),
        migrations.AlterField(
            model_name='user',
            name='failedAttempts',
            field=models.IntegerField(default=5, verbose_name='Login Failure'),
        ),
    ]
