# Generated by Django 2.0 on 2018-01-09 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amazonassociates',
            old_name='secrecy_access_key',
            new_name='secrect_access_key',
        ),
    ]
