# Generated by Django 2.0 on 2018-01-09 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20180109_1233'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='amazonassociates',
            unique_together={('country', 'associate_tag')},
        ),
    ]
