# Generated by Django 2.0 on 2018-01-22 15:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0100_amazonassociates_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonassociates',
            name='date_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
