# Generated by Django 2.0 on 2018-01-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0101_amazonassociates_date_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonassociates',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
