# Generated by Django 2.0.1 on 2018-01-28 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0102_auto_20180122_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='CacheAmazonSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('asin', models.CharField(max_length=50, verbose_name='Asin')),
                ('large_image_url', models.CharField(max_length=255, verbose_name='Image')),
                ('availability', models.CharField(max_length=100, verbose_name='Availability')),
                ('detail_page_url', models.CharField(max_length=400, verbose_name='Detail')),
                ('price_and_currency', models.CharField(max_length=20, verbose_name='Price')),
                ('offer_url', models.CharField(max_length=255, verbose_name='Offer')),
                ('features', models.TextField(verbose_name='Description')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amazon_user_cache', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
