# Generated by Django 2.0 on 2018-01-10 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('type_card', models.CharField(blank=True, choices=[('visa', 'Visa'), ('mastercard', 'MasterCard'), ('americanexpress', 'AmericanExpress'), ('maestro', 'Maestro')], max_length=20, verbose_name='Type_Card')),
                ('number_card', models.CharField(max_length=20, verbose_name='Number_Card')),
                ('cod_security', models.CharField(max_length=4, verbose_name='Cod_Security')),
                ('date_creation', models.DateField()),
                ('date_expiration', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('cost', models.FloatField(default=0, verbose_name='Plan_Cost')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('number_card', models.CharField(max_length=20, verbose_name='Number_Card')),
                ('cod_security', models.CharField(max_length=4, verbose_name='Cod_Security')),
                ('date_creation', models.DateField()),
                ('date_expiration', models.DateField()),
                ('date_start', models.DateTimeField()),
                ('date_finish', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('type_plan', models.CharField(max_length=20, verbose_name='Type_plan')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='image')),
                ('cost', models.FloatField(default=0, verbose_name='Plan_Cost')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('terms', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('accept', models.BooleanField(default=False, help_text='Accept the terms and conditions?', verbose_name='Accept')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PlanSubscriptionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Title')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TermsCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='plansubscription',
            name='list',
            field=models.ManyToManyField(blank=True, to='payment.PlanSubscriptionList', verbose_name='PlanSubscriptionLists'),
        ),
    ]
