# Generated by Django 2.0 on 2018-01-11 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='cod_security',
            field=models.CharField(max_length=4, verbose_name='Code_Security'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='type_card',
            field=models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'MasterCard'), ('americanexpress', 'AmericanExpress'), ('maestro', 'Maestro')], max_length=20, verbose_name='Type_Card'),
        ),
        migrations.AlterField(
            model_name='plansubscription',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='plansubscription',
            name='terms',
            field=models.TextField(verbose_name='TermsCondition'),
        ),
        migrations.AlterField(
            model_name='plansubscriptionlist',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='termscondition',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
