# Generated by Django 2.0 on 2018-01-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20180111_0247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plansubscription',
            name='accept',
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='accept',
            field=models.BooleanField(default=False, help_text='Accept the terms and conditions?', verbose_name='Accept'),
        ),
    ]
