# Generated by Django 2.0 on 2018-01-16 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20180115_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plansubscription',
            name='duration',
            field=models.CharField(blank=True, choices=[('1 mounth', '1 mounth')], default='1 mounth', max_length=50, null=True, verbose_name='Duration'),
        ),
    ]
