# Generated by Django 2.0 on 2018-01-16 19:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_auto_20180116_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelsubscription',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cancelsubscription',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
