# Generated by Django 2.0 on 2018-01-16 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_auto_20180116_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancelsubscription',
            name='id_plan',
        ),
        migrations.AddField(
            model_name='cancelsubscription',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancel_plan', to='payment.PlanSubscription'),
        ),
    ]
