# Generated by Django 2.0.1 on 2018-01-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_auto_20180116_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='type_card',
            field=models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'MasterCard'), ('americanexpress', 'AmericanExpress'), ('maestro', 'Maestro'), ('discover', 'Discover')], max_length=20, verbose_name='Type_Card'),
        ),
    ]
