# Generated by Django 2.0.1 on 2018-01-25 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_auto_20180125_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelsubscription',
            name='option',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Option'),
            preserve_default=False,
        ),
    ]
