# Generated by Django 2.0.1 on 2018-01-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_cancelsubscription_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='payerID',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='paymentId',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Plan_Cost'),
        ),
        migrations.AlterField(
            model_name='plansubscription',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Plan_Cost'),
        ),
        migrations.AlterField(
            model_name='plansubscription',
            name='duration',
            field=models.CharField(blank=True, choices=[('1 mounth', '1 mounth'), ('1 year', '1 year')], default='1 mounth', max_length=50, null=True, verbose_name='Duration'),
        ),
    ]
