# Generated by Django 2.0.1 on 2018-02-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0017_auto_20180202_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='First_name'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Last_name'),
        ),
    ]
