# Generated by Django 2.0.1 on 2018-04-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0021_plansubscription_automatic_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansubscription',
            name='number_search',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of search'),
        ),
        migrations.AddField(
            model_name='plansubscription',
            name='unlimited_search',
            field=models.BooleanField(default=False, help_text='Accept unlimited searches?', verbose_name='Automatic'),
        ),
    ]
