# Generated by Django 2.0.1 on 2018-04-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0023_auto_20180416_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='number_search',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of search'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='unlimited_search',
            field=models.BooleanField(default=False, help_text='Accept unlimited searches?', verbose_name='Unlimited Search'),
        ),
    ]
