# Generated by Django 2.0.1 on 2019-04-20 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0024_auto_20180416_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='days_free',
            field=models.IntegerField(blank=True, null=True, verbose_name='days_free'),
        ),
    ]
