# Generated by Django 2.0 on 2018-01-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsupport',
            name='message',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
